services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/sonarr/config:/config
      - /mnt/tv:/tv
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
