services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entrypoints: http
      traefik.http.routers.sonarr.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.sonarr.middlewares: sonarr-https-redirect
      traefik.http.routers.sonarr-secure.entrypoints: https
      traefik.http.routers.sonarr-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.sonarr-secure.tls: true
      traefik.http.routers.sonarr-secure.service: sonarr
      traefik.http.routers.sonarr-secure.middlewares: secured@file
      traefik.http.services.sonarr.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /opt/docker/appdata/sonarr/config:/config
      - /mnt/tv:/tv
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
