services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.19.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://127.0.0.1:8090"]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 5
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.beszel.rule: "Host(`beszel.zech.co`)"
      traefik.http.routers.beszel.entrypoints: "websecure"
      traefik.http.routers.beszel.tls: "true"
      traefik.http.routers.beszel.middlewares: "security-headers@file,compression@file"
      traefik.http.services.beszel.loadbalancer.server.port: "8090"
    environment:
      DISABLE_PASSWORD_AUTH: true
    volumes:
      - ../../appdata/beszel:/beszel_data
    networks:
      - proxy

networks:
  proxy:
    external: true
