services:
  database:
    container_name: speedtest-tracker-database
    image: postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/docker/appdata/speedtest-tracker/database:/var/lib/postgresql/data
    networks:
      - speedtest-tracker

  speedtest-tracker:
    container_name: speedtest-tracker
    image: linuxserver/speedtest-tracker:1.3.0
    restart: unless-stopped
    ports:
      - "8088:80"
    env_file:
      - .env
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - /opt/docker/appdata/speedtest-tracker/config:/config
    networks:
      - proxy
      - speedtest-tracker
    depends_on:
      - database

networks:
  proxy:
    external: true
  speedtest-tracker:
    external: true