services:
  changedetection:
    container_name: changedetection
    image: dgtlmoon/changedetection.io
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.changedetection.entrypoints: http
      traefik.http.routers.changedetection.rule: Host(`change.${DOMAIN_NAME}`)
      traefik.http.middlewares.changedetection-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.changedetection.middlewares: changedetection-https-redirect
      traefik.http.routers.changedetection-secure.entrypoints: https
      traefik.http.routers.changedetection-secure.rule: Host(`change.${DOMAIN_NAME}`)
      traefik.http.routers.changedetection-secure.tls: true
      traefik.http.routers.changedetection-secure.service: changedetection
      traefik.http.routers.changedetection-secure.middlewares: secured@file
      traefik.http.services.changedetection.loadbalancer.server.port: 5000
      traefik.docker.network: proxy
    volumes:
      - ./changedetection/datastore:/datastore
    networks:
      - proxy

networks:
  proxy:
    external: true

