services:
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf
    restart: unless-stopped
    volumes:
      - /opt/docker/appdata/audiobookshelf/config:/config
      - /opt/docker/appdata/audiobookshelf/metadata:/metadata
      - /mnt/library/audiobooks:/audiobooks
      - /mnt/library/podcasts:/podcasts
    networks:
      - proxy

networks:
  proxy:
    external: true
