version: "3"

services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entrypoints: http
      traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN_NAME}`)
      traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.sonarr.middlewares: sonarr-https-redirect
      traefik.http.routers.sonarr-secure.entrypoints: https
      traefik.http.routers.sonarr-secure.rule: Host(`sonarr.${DOMAIN_NAME}`)
      traefik.http.routers.sonarr-secure.tls: true
      traefik.http.routers.sonarr-secure.service: sonarr
      traefik.http.routers.sonarr-secure.middlewares: authentik@file
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
      traefik.docker.network: proxy
    volumes:
      - ./sonarr/config:/config
      - /mnt/tv:/tv
      - /mnt/downloads:/downloads
    networks:
      - proxy
      - media
    
networks:
  proxy: 
    external: true
  media:
    external: true
