services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.it-tools.entrypoints: http
      traefik.http.routers.it-tools.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.it-tools-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.it-tools.middlewares: it-tools-https-redirect
      traefik.http.routers.it-tools-secure.entrypoints: https
      traefik.http.routers.it-tools-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.it-tools-secure.tls: true
      traefik.http.routers.it-tools-secure.service: it-tools
      traefik.http.routers.it-tools-secure.middlewares: default-headers@file
      traefik.http.services.it-tools.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    networks:
      - proxy

networks:
  proxy:
    external: true
