version: "3"
 
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.entrypoints: http
      traefik.http.routers.qbittorrent.rule: Host(`torrent.${DOMAIN_NAME}`)
      traefik.http.middlewares.qbittorrent-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.qbittorrent.middlewares: qbittorrent-https-redirect
      traefik.http.routers.qbittorrent-secure.entrypoints: https
      traefik.http.routers.qbittorrent-secure.rule: Host(`torrent.${DOMAIN_NAME}`)
      traefik.http.routers.qbittorrent-secure.tls: true
      traefik.http.routers.qbittorrent-secure.service: qbittorrent
      traefik.http.routers.qbittorrent-secure.middlewares: secured@file
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.docker.network: proxy
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/downloads:/downloads
    networks:
      - proxy
      - media
    
networks:
  proxy:
    external: true
  media:
    external: true
