services:
  whatsupdocker:
    container_name: whatsupdocker
    image: fmartinou/whats-up-docker
    restart: unless-stopped
    ports:
      - 3005:3000
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
