services:
  hoarder:
    container_name: hoarder
    image:  ghcr.io/hoarder-app/hoarder:release
    restart: unless-stopped
    ports:
      - 3002:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
    volumes:
      - /opt/docker/appdata/hoarder/data:/data
    networks:
      - hoarder
    depends_on:
      - chrome
      - meilisearch

  chrome:
    container_name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    labels:
      - wud.watch=false
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder

  meilisearch:
    container_name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.12
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - wud.watch=false
    volumes:
      - /opt/docker/appdata/hoarder/meilisearch:/meili_data
    networks:
      - hoarder

networks:
  proxy:
    external: true
  hoarder:
    external: true

