services:
  databasus:
    container_name: databasus
    image: databasus/databasus:v3.55.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "databasus", "healthcheck"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.databasus.rule: "Host(`databasus.zech.co`)"
      traefik.http.routers.databasus.entrypoints: "websecure"
      traefik.http.routers.databasus.tls: "true"
      traefik.http.routers.databasus.middlewares: "internal-only@file,security-headers@file,compression@file"
      traefik.http.services.databasus.loadbalancer.server.port: "4005"
    volumes:
      - ../../appdata/databasus:/databasus-data
    networks:
      - proxy
      - database-backup

networks:
  proxy:
    external: true

  database-backup:
    external: true
