services:
  isponsorblocktv:
    container_name: isponsorblocktv
    image: ghcr.io/dmunozv04/isponsorblocktv:v2.11.0
    restart: unless-stopped
    network_mode: host
    volumes:
    - ../../appdata/isponsorblocktv:/app/data
