services:
  database:
    container_name: sparkyfitness-database
    image: postgres:18.6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../../appdata/sparkyfitness/postgresql:/var/lib/postgresql
    networks:
      - internal

  server:
    container_name: sparkyfitness-server
    image: codewithcj/sparkyfitness_server:v1.6.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:3010/health', response => process.exit(response.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      SPARKY_FITNESS_DB_HOST: database
      SPARKY_FITNESS_DB_PORT: 5432
      SPARKY_FITNESS_DB_NAME: ${DATABASE_NAME}
      SPARKY_FITNESS_DB_USER: ${DATABASE_USER}
      SPARKY_FITNESS_DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../../appdata/sparkyfitness/backup:/app/SparkyFitnessServer/backup
      - ../../appdata/sparkyfitness/uploads:/app/SparkyFitnessServer/uploads
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: sparkyfitness-frontend
    image: codewithcj/sparkyfitness:v1.6.4
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.sparkyfitness.rule: "Host(`health.zech.co`)"
      traefik.http.routers.sparkyfitness.entrypoints: "websecure"
      traefik.http.routers.sparkyfitness.tls: "true"
      traefik.http.routers.sparkyfitness.middlewares: "security-headers@file,compression@file"
      traefik.http.services.sparkyfitness.loadbalancer.server.port: "80"
    environment:
      SPARKY_FITNESS_FRONTEND_URL: ${SPARKY_FITNESS_FRONTEND_URL}
      SPARKY_FITNESS_SERVER_HOST: sparkyfitness-server
      SPARKY_FITNESS_SERVER_PORT: 3010
    networks:
      - proxy
      - internal
    depends_on:
      - server

networks:
  proxy:
    external: true

  internal:
    name: sparkyfitness-internal
    driver: bridge
