version: "3"

services:
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr
    restart: unless-stopped
    ports:
      - 8266:8266
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
      serverPort: 8266
      webUIPort: 8265
      internalNode: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.entrypoints=http"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.tdarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tdarr.middlewares=tdarr-https-redirect"
      - "traefik.http.routers.tdarr-secure.entrypoints=https"
      - "traefik.http.routers.tdarr-secure.rule=Host(`tdarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.tdarr-secure.tls=true"
      - "traefik.http.routers.tdarr-secure.service=tdarr"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
      - "traefik.docker.network=proxy"
    volumes:
      - ./tdarr/logs:/app/logs
      - ./tdarr/server:/app/server
      - ./tdarr/configs:/app/configs
      - /mnt/temp:/temp
      - /mnt/movies:/mnt/media/Movies
      - /mnt/tv:/mnt/media/TV
    networks:
      - proxy

networks:
  proxy: 
    external: true
