services:
  apprise:
    container_name: apprise
    image: caronc/apprise:1.5.1
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.apprise.rule: "Host(`apprise.zech.co`)"
      traefik.http.routers.apprise.entrypoints: "websecure"
      traefik.http.routers.apprise.tls: "true"
      traefik.http.routers.apprise.middlewares: "internal-only@file,security-headers@file,compression@file"
      traefik.http.routers.apprise.service: "apprise"
      traefik.http.services.apprise.loadbalancer.server.port: "8000"
    environment:
      APPRISE_STATEFUL_MODE: hash
      APPRISE_WORKER_COUNT: "1"
      APPRISE_ADMIN: "y"
    volumes:
      - /opt/appdata/apprise/config:/config
      - /opt/appdata/apprise/attach:/attach
      - /opt/appdata/apprise/plugin:/plugin
    tmpfs:
      - /tmp
    networks:
      - proxy

networks:
  proxy:
    external: true
