services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GF_SERVER_ROOT_URL: https://${BASE_URL}
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: http
      traefik.http.routers.grafana.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.grafana.middlewares: grafana-https-redirect
      traefik.http.routers.grafana-secure.entrypoints: https
      traefik.http.routers.grafana-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.grafana-secure.tls: true
      traefik.http.routers.grafana-secure.service: grafana
      traefik.http.routers.grafana-secure.middlewares: default-headers@file
      traefik.http.services.grafana.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /opt/docker/appdata/grafana:/var/lib/grafana
    networks:
      - proxy
      - monitoring

networks:
  proxy:
    external: true
  monitoring:
    external: true
