services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/grafana:/var/lib/grafana
    networks:
      - proxy
      - monitoring

networks:
  proxy:
    external: true
  monitoring:
    external: true
