services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entrypoints: http
      traefik.http.routers.radarr.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.radarr.middlewares: radarr-https-redirect
      traefik.http.routers.radarr-secure.entrypoints: https
      traefik.http.routers.radarr-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.radarr-secure.tls: true
      traefik.http.routers.radarr-secure.service: radarr
      traefik.http.routers.radarr-secure.middlewares: secured@file
      traefik.http.services.radarr.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /opt/docker/appdata/radarr/config:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
