services:
  doku:
    container_name: doku
    image: amerkurev/doku:v1.1.0
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
