services:
  database:
    container_name: wikijs-database
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/docker/appdata/wikijs/database:/var/lib/postgresql/data
    networks:
      - wikijs

  wikijs:
    container_name: wikijs
    image: requarks/wiki
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_TYPE: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASS: ${DATABASE_PASSWORD}
    labels:
      traefik.enable: true
      traefik.http.routers.wikijs.entrypoints: http
      traefik.http.routers.wikijs.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.wikijs-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.wikijs.middlewares: wikijs-https-redirect
      traefik.http.routers.wikijs-secure.entrypoints: https
      traefik.http.routers.wikijs-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.wikijs-secure.tls: true
      traefik.http.routers.wikijs-secure.service: wikijs
      traefik.http.services.wikijs.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    networks:
      - proxy
      - wikijs
    depends_on:
      - database

networks:
  proxy:
    external: true
  wikijs:
    external: true
