services:
  healthchecks:
    container_name: healthchecks
    image: linuxserver/healthchecks
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.healthchecks.entrypoints: http
      traefik.http.routers.healthchecks.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.healthchecks-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.healthchecks.middlewares: healthchecks-https-redirect
      traefik.http.routers.healthchecks-secure.entrypoints: https
      traefik.http.routers.healthchecks-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.healthchecks-secure.tls: true
      traefik.http.routers.healthchecks-secure.service: healthchecks
      traefik.http.routers.healthchecks-secure.middlewares: default-headers@file
      traefik.http.services.healthchecks.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /opt/docker/appdata/healthchecks/config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
