services:
  healthchecks:
    container_name: healthchecks
    image: linuxserver/healthchecks
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/healthchecks/config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
