services:
  database:
    container_name: immich-database
    image: ghcr.io/immich-app/postgres:18-vectorchord1.1.1-pgvector0.8.5
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ../../appdata/immich/database:/var/lib/postgresql
    networks:
      - internal
      - database-backup

  valkey:
    container_name: immich-valkey
    image: valkey/valkey:9.1.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../../appdata/immich/valkey:/data
    networks:
      - internal

  server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v3.1.0
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.immich.rule: "Host(`photos.zech.co`)"
      traefik.http.routers.immich.entrypoints: "websecure"
      traefik.http.routers.immich.tls: "true"
      traefik.http.routers.immich.middlewares: "security-headers@file,compression@file"
      traefik.http.services.immich.loadbalancer.server.port: "2283"
    environment:
      TZ: Europe/Vienna
      DB_HOSTNAME: database
      DB_DATABASE_NAME: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOSTNAME: valkey
      IMMICH_MACHINE_LEARNING_URL: http://machine-learning:3003
    volumes:
      - /mnt/immich:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - internal
    depends_on:
      database:
        condition: service_healthy
      valkey:
        condition: service_healthy

  machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v3.1.0
    restart: unless-stopped
    volumes:
      - /mnt/immich/machine-learning:/cache
    networks:
      - internal

networks:
  proxy:
    external: true

  database-backup:
    external: true

  internal:
    name: immich-internal
    driver: bridge
