services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:2.5.1
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      TZ: Europe/Vienna
    volumes:
      - /opt/docker/appdata/jellyseerr/config:/app/config
    networks:
      - proxy

networks:
  proxy:
    external: true
