---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

useEqualHeights: true

layout:
  Infrastructure:
    style: row
    columns: 4
  Media:
    style: row
    columns: 4
  Productivity:
    style: row
    columns: 4
  Personal:
    style: row
    columns: 4
  Utilities:
    style: row
    columns: 4
  Gaming:
    style: row
    columns: 4
  Calendars:
    style: row
    columns: 4
