services:
  readarr:
    container_name: readarr
    image: linuxserver/readarr:develop
    restart: unless-stopped
    ports:
      - 8787:8787
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/readarr/config:/config
      - /mnt/library/books:/books
      - /mnt/library/audiobooks:/audiobooks
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
