services:
  database:
    container_name: speedtest-tracker-database
    image: postgres:18.4-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/appdata/speedtest-tracker/postgres:/var/lib/postgresql
    networks:
      - internal

  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:1.14.6
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost/api/healthcheck | jq -e '.message == \"Speedtest Tracker is running!\"' > /dev/null || exit 1"]
      start_period: 30s
      interval: 30s
      retries: 3
      timeout: 10s
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.speedtest-tracker.rule: "Host(`speedtest.zech.co`)"
      traefik.http.routers.speedtest-tracker.entrypoints: "websecure"
      traefik.http.routers.speedtest-tracker.tls: "true"
      traefik.http.routers.speedtest-tracker.middlewares: "security-headers@file,compression@file"
      traefik.http.services.speedtest-tracker.loadbalancer.server.port: "80"
    env_file:
      - .env
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/appdata/speedtest-tracker/config:/config
    networks:
      - proxy
      - internal
    depends_on:
      database:
        condition: service_healthy

networks:
  proxy:
    external: true

  internal:
    name: speedtest-tracker-internal
    driver: bridge