services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: ghcr.io/alexjustesen/speedtest-tracker
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: pgsql
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedtest_tracker
      DB_PASSWORD: ${POSTGRES_SPEEDTEST_TRACKER_PASS}
    labels:
      traefik.enable: true
      traefik.http.routers.speedtest-tracker.entrypoints: http
      traefik.http.routers.speedtest-tracker.rule: Host(`speedtest.${DOMAIN_NAME}`)
      traefik.http.middlewares.speedtest-tracker-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.speedtest-tracker.middlewares: speedtest-tracker-https-redirect
      traefik.http.routers.speedtest-tracker-secure.entrypoints: https
      traefik.http.routers.speedtest-tracker-secure.rule: Host(`speedtest.${DOMAIN_NAME}`)
      traefik.http.routers.speedtest-tracker-secure.tls: true
      traefik.http.routers.speedtest-tracker-secure.service: speedtest-tracker
      traefik.http.routers.speedtest-tracker-secure.middlewares: default-headers@file
      traefik.http.services.speedtest-tracker.loadbalancer.server.port: 80
      traefik.docker.network: proxy
    volumes:
      - ./speedtest-tracker/config:/config
    env_file:
      - .env
    networks:
      - proxy
      - database

networks:
  proxy:
    external: true
  database:
    external: true