services:
  database:
    container_name: astroluma-database
    image: mongo:6
    restart: unless-stopped
    volumes:
      - /opt/docker/appdata/astroluma/database:/data/db
    networks:
      - astroluma

  astroluma:
    container_name: astroluma
    image: sanjeet990/astroluma:1.0.2
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      NODE_ENV: production
      SECRET_KEY: a2c5f9a8b2d7e1a7f2c9c8d9b5f7a3d5
      MONGODB_URI: mongodb://database:27017/astroluma
    volumes:
      - /opt/docker/appdata/astroluma/uploads:/app/storage/uploads
      - /opt/docker/appdata/astroluma/apps:/app/storage/apps
    networks:
      - proxy
      - astroluma
    depends_on:
      - database

networks:
  proxy:
    external: true
  astroluma:
    external: true
