services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    build:
      context: .
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/appdata/caddy/config:/config
      - /opt/docker/appdata/caddy/data:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
