version: "3"

services:
  paperless:
    container_name: paperless
    image: paperless-ngx/paperless-ngx
    restart: unless-stopped
    environment:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_DBHOST: postgresql
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBPASS: ${POSTGRES_PAPERLESS_PASS}
      PAPERLESS_DBUSER: paperless
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: TRUE
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_REDIS: paperless-redis
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET}
      PAPERLESS_TIME_ZONE: Europe/Vienna
      PAPERLESS_URL: https://${PAPERLESS_BASE_URL}
      PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS}
    labels:
      traefik.enable: true
      traefik.http.routers.paperless.entrypoints: http
      traefik.http.routers.paperless.rule: Host(`hpaperless.${DOMAIN_NAME}`)
      traefik.http.middlewares.paperless-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.paperless.middlewares: hpaperless-https-redirect
      traefik.http.routers.paperless-secure.entrypoints: https
      traefik.http.routers.paperless-secure.rule: Host(`hpaperless.${DOMAIN_NAME}`)
      traefik.http.routers.paperless-secure.tls: true
      traefik.http.routers.paperless-secure.service: hpaperless
      traefik.http.routers.paperless-secure.middlewares: authentik@file
      traefik.http.services.paperless.loadbalancer.server.port: 8000
      traefik.docker.network: proxy
    volumes:
      - ./paperless/config:/config
      - ./paperless/data:/data
    networks:
      - proxy
      - paperless
      - database

  paperless-redis:
    container_name: paperless-redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./paperless/redis:/data
    networks:
      - paperless

networks:
  proxy: 
    external: true
  paperless: 
    external: true
  database:
    external: true
