services:
  dockge:
    container_name: dockge
    image: louislam/dockge
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.dockge.entrypoints: http
      traefik.http.routers.dockge.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.dockge-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.dockge.middlewares: dockge-https-redirect
      traefik.http.routers.dockge-secure.entrypoints: https
      traefik.http.routers.dockge-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.dockge-secure.tls: true
      traefik.http.routers.dockge-secure.service: dockge
      traefik.http.routers.dockge-secure.middlewares: secured@file
      traefik.http.services.dockge.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/appdata/dockge/data:/app/data
      - /opt/docker/applications:/opt/stacks
    networks:
      - proxy

networks:
  proxy:
    external: true
