services:
  dockge:
    container_name: dockge
    image: louislam/dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/appdata/dockge/data:/app/data
      - /opt/docker/applications:/opt/stacks
    networks:
      - proxy

networks:
  proxy:
    external: true
