services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/appdata/homepage/config:/app/config
    networks:
      - proxy

networks:
  proxy:
    external: true
