services:
  database:
    container_name: authentik-database
    image: postgres:18.6
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/appdata/authentik/database:/var/lib/postgresql
    networks:
      - internal
      - database-backup

  server:
    container_name: authentik-server
    image: ghcr.io/goauthentik/server:2026.8.0
    restart: unless-stopped
    command: server
    healthcheck:
      test: ["CMD", "ak", "healthcheck"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 5
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.authentik.rule: "Host(`sso.zech.co`)"
      traefik.http.routers.authentik.entrypoints: "websecure"
      traefik.http.routers.authentik.tls: "true"
      traefik.http.routers.authentik.middlewares: "compression@file"
      traefik.http.services.authentik.loadbalancer.server.port: "9000"
      traefik.http.routers.authentik-outpost.rule: "PathPrefix(`/outpost.goauthentik.io/`)"
      traefik.http.routers.authentik-outpost.entrypoints: "websecure"
      traefik.http.routers.authentik-outpost.tls: "true"
      traefik.http.routers.authentik-outpost.priority: "100"
      traefik.http.routers.authentik-outpost.service: "authentik"
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: database
      AUTHENTIK_POSTGRESQL__NAME: ${DATABASE_NAME}
      AUTHENTIK_POSTGRESQL__USER: ${DATABASE_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/appdata/authentik/data:/data
      - /opt/appdata/authentik/templates:/templates
    networks:
      - proxy
      - internal
    depends_on:
      database:
        condition: service_healthy

  worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:2026.8.0
    restart: unless-stopped
    command: worker
    healthcheck:
      test: ["CMD", "ak", "healthcheck"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: database
      AUTHENTIK_POSTGRESQL__NAME: ${DATABASE_NAME}
      AUTHENTIK_POSTGRESQL__USER: ${DATABASE_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/appdata/authentik/data:/data
      - /opt/appdata/authentik/templates:/templates
      - /opt/appdata/authentik/certs:/certs
    networks:
      - internal
      - socket-proxy
    depends_on:
      database:
        condition: service_healthy
      socket-proxy:
        condition: service_started

  socket-proxy:
    container_name: authentik-socket-proxy
    image: tecnativa/docker-socket-proxy:v0.5.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://127.0.0.1:2375/version"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      CONTAINERS: 1
      IMAGES: 1
      INFO: 1
      POST: 1
      ALLOW_RESTARTS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy

networks:
  proxy:
    external: true

  database-backup:
    external: true

  internal:
    name: authentik-internal
    driver: bridge

  socket-proxy:
    internal: true
