version: "3"

services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routershomepage.entrypoints=http"
      - "traefik.http.routershomepage.rule=Host(`home.${DOMAIN_NAME}`)"
      - "traefik.http.middlewareshomepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routershomepage.middlewares=home-https-redirect"
      - "traefik.http.routershomepage-secure.entrypoints=https"
      - "traefik.http.routershomepage-secure.rule=Host(`home.${DOMAIN_NAME}`)"
      - "traefik.http.routershomepage-secure.tls=true"
      - "traefik.http.routershomepage-secure.service=home"
      - "traefik.http.serviceshomepage.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homepage/config:/app/config
    networks:
      - proxy
  
  homepage_code-server:
    container_name: homepage_code-server
    image: linuxserver/code-server
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
      PROXY_DOMAIN: home.${DOMAIN_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routershomepage.entrypoints=http"
      - "traefik.http.routershomepage.rule=Host(`home.${DOMAIN_NAME}` && Path(`/traefik`))"
      - "traefik.http.middlewareshomepage-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routershomepage.middlewares=home-https-redirect"
      - "traefik.http.routershomepage-secure.entrypoints=https"
      - "traefik.http.routershomepage-secure.rule=Host(`home.${DOMAIN_NAME}` && Path(`/traefik`))"
      - "traefik.http.routershomepage-secure.tls=true"
      - "traefik.http.routershomepage-secure.service=home"
      - "traefik.http.serviceshomepage.loadbalancer.server.port=8443"
      - "traefik.docker.network=proxy"
    volumes:
      - ./homepage_code-server/config:/config
      - ./homepage/config:/app/config
    networks:
      - proxy

networks:
  proxy: 
    external: true
