version: "3"

services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.entrypoints: http
      traefik.http.routers.homepage.rule: Host(`home.${DOMAIN_NAME}`)
      traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.homepage.middlewares: home-https-redirect
      traefik.http.routers.homepage-secure.entrypoints: https
      traefik.http.routers.homepage-secure.rule: Host(`home.${DOMAIN_NAME}`)
      traefik.http.routers.homepage-secure.tls: true
      traefik.http.routers.homepage-secure.service: home
      traefik.http.routers.homepage-secure.middlewares: secured@file
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      traefik.docker.network: proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homepage/config:/app/config
    networks:
      - proxy
  
  homepage_code-server:
    container_name: homepage_code-server
    image: linuxserver/code-server
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
      PROXY_DOMAIN: home.${DOMAIN_NAME}
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.entrypoints: http
      traefik.http.routers.homepage.rule: Host(`home.${DOMAIN_NAME}` && Path(`/edit`))
      traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.homepage.middlewares: home-https-redirect
      traefik.http.routers.homepage-secure.entrypoints: https
      traefik.http.routers.homepage-secure.rule: Host(`home.${DOMAIN_NAME}` && Path(`/edit`))
      traefik.http.routers.homepage-secure.tls: true
      traefik.http.routers.homepage-secure.service: home
      traefik.http.routers.homepage-secure.middlewares: secured@file
      traefik.http.services.homepage.loadbalancer.server.port: 8443
      traefik.docker.network: proxy
    volumes:
      - ./homepage_code-server/config:/config
      - ./homepage/config:/app/config
    networks:
      - proxy

networks:
  proxy: 
    external: true
