services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:4.4.1
    restart: unless-stopped
    ports:
      - "8087:8080"
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/sabnzbd/config:/config
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
