services:
  youtube-dl:
    container_name: youtube-dl
    image: linuxserver/code-server:4.104.0
    restart: unless-stopped
    ports:
      - "8444:8443"
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/youtube-dl/ytdl:/ytdl
      - /opt/docker/appdata/youtube-dl/config:/config
      - /mnt/private:/private
    networks:
      - proxy

networks:
  proxy:
    external: true
