services:
  youtube-dl:
    container_name: youtube-dl
    image: linuxserver/code-server:4.96.4
    restart: unless-stopped
    ports:
      - "8444:8443"
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
      DOCKER_MODS: linuxserver/mods:code-server-python3
      PROXY_DOMAIN: ${PROXY_DOMAIN}
    volumes:
      - /opt/docker/appdata/youtube-dl/ytdl:/ytdl
      - /opt/docker/appdata/youtube-dl/config:/config
      - /mnt/private:/private
    networks:
      - proxy

networks:
  proxy:
    external: true
