services:
  free-games-claimer:
    container_name: free-games-claimer
    image: ghcr.io/vogler/free-games-claimer
    restart: unless-stopped
    command: bash -c "node epic-games node prime-gaming; node gog; node; echo sleeping; sleep 1d; docker restart free-games-claimer"
    ports:
    - 6080:6080
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/free-games-claimer/data:/fgc/data
    networks:
      - proxy

networks:
  proxy:
    external: true
