version: "3"

services:
  postgresql:
    container_name: postgresql
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - database

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_DISABLE_POSTFIX: True
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: True
      PGADMIN_CONFIG_AUTHENTICATION_SOURCES: "['oauth2', 'internal']"
      PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: True
      PGADMIN_CONFIG_OAUTH2_NAME: authentik
      PGADMIN_CONFIG_OAUTH2_DISPLAY_NAME: Authentik
      PGADMIN_CONFIG_OAUTH2_CLIENT_ID: ${PGADMIN_CLIENT_ID}
      PGADMIN_CONFIG_OAUTH2_CLIENT_SECRET: ${PGADMIN_CLIENT_SECRET}
      PGADMIN_CONFIG_OAUTH2_TOKEN_URL: ${AUTHENTIK_BASE_URL}/application/o/token/
      PGADMIN_CONFIG_OAUTH2_AUTHORIZATION_URL: ${AUTHENTIK_BASE_URL}/application/authorize/token/
      PGADMIN_CONFIG_OAUTH2_API_BASE_URL: ${AUTHENTIK_BASE_URL}/
      PGADMIN_CONFIG_OAUTH2_USERINFO_ENDPOINT: ${AUTHENTIK_BASE_URL}/application/o/userinfo/
      PGADMIN_CONFIG_OAUTH2_SERVER_METADATA_URL: ${AUTHENTIK_BASE_URL}/application/o/{PGADMIN_SLUG}/.well-known/openid-configuration/
      PGADMIN_CONFIG_OAUTH2_BUTTON_COLOR: '#3253a8'
      PGADMIN_CONFIG_OAUTH2_SCOPE: openid email profile
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    networks:
      - database
      - proxy

networks:
  database: 
    external: true
  proxy: 
    external: true