version: "3"

services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
    volumes:
      - ./sabnzbd/config:/config
      - /mnt/downloads:/downloads
    networks:
      - proxy
      - media
    
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/downloads:/downloads
    networks:
      - proxy
      - media
    



  youtube-dl_code-server:
    container_name: outube-dl_code-server
    image: linuxserver/code-server
    restart: unless-stopped
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Europe/Vienna
      PROXY_DOMAIN: editdash.zech.co
    volumes:
      - ./outube-dl_code-server/config:/config
      - /mnt/private:/private
    networks:
      - proxy

networks:
  proxy:
    external: true
  media:
    external: true
