version: "3"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_HTTP_API_METRICS: true
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy: 
    external: true
    