tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true

  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: zech.co
          sans:
            - "*.zech.co"
