services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    ports:
    - 8098:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
