services:
  doku:
    container_name: doku
    image: amerkurev/doku
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
