services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.routers.portainer.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.portainer.middlewares: portainer-https-redirect
      traefik.http.routers.portainer-secure.entrypoints: https
      traefik.http.routers.portainer-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.portainer-secure.tls: true
      traefik.http.routers.portainer-secure.service: portainer
      traefik.http.routers.portainer-secure.middlewares: default-headers@file
      traefik.http.services.portainer.loadbalancer.server.scheme: https
      traefik.http.services.portainer.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/appdata/portainer/data:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
