services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:5.1.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://127.0.0.1:8080/"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.sabnzbd.rule: "Host(`sabnzbd.zech.co`)"
      traefik.http.routers.sabnzbd.entrypoints: "websecure"
      traefik.http.routers.sabnzbd.tls: "true"
      traefik.http.routers.sabnzbd-api.rule: "Host(`sabnzbd.zech.co`) && (Path(`/api`) || PathPrefix(`/api/`))"
      traefik.http.routers.sabnzbd-api.entrypoints: "websecure"
      traefik.http.routers.sabnzbd-api.tls: "true"
      traefik.http.routers.sabnzbd-api.priority: "100"
      traefik.http.routers.sabnzbd-api.middlewares: "security-headers@file,compression@file"
      traefik.http.routers.sabnzbd-api.service: "sabnzbd"
      traefik.http.routers.sabnzbd.middlewares: "authentik@file,security-headers@file,compression@file"
      traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"
    environment:
      TZ: Europe/Vienna
      PUID: 1000
      PGID: 1000
    volumes:
      - ../../appdata/sabnzbd/config:/config
      - /mnt/downloads/complete:/downloads
      - /mnt/downloads/incomplete:/incomplete-downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
