services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.21.1
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/radarr/config:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
