services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:5.1.2
    restart: unless-stopped
    ports:
      - "8086:8080"
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/qbittorrent/config:/config
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
