services:
  picoshare:
    container_name: picoshare
    image: mtlynch/picoshare
    restart: unless-stopped
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.picoshare.entrypoints: http
      traefik.http.routers.picoshare.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.picoshare-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.picoshare.middlewares: picoshare-https-redirect
      traefik.http.routers.picoshare-secure.entrypoints: https
      traefik.http.routers.picoshare-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.picoshare-secure.tls: true
      traefik.http.routers.picoshare-secure.service: picoshare
      traefik.http.routers.picoshare-secure.middlewares: default-headers@file
      traefik.http.services.picoshare.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /opt/docker/appdata/picoshare/data:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
