services:
  picoshare:
    container_name: picoshare
    image: mtlynch/picoshare
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/picoshare/data:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
