services:
  database:
    container_name: paperless-database
    image: postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/docker/appdata/paperless/database:/var/lib/postgresql/data
    networks:
      - paperless

  paperless:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:2.17.1
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      PAPERLESS_DBHOST: database
      PAPERLESS_DBNAME: ${DATABASE_NAME}
      PAPERLESS_DBUSER: ${DATABASE_USER}
      PAPERLESS_DBPASS: ${DATABASE_PASSWORD}
    volumes:
      - /opt/docker/appdata/paperless/data:/usr/src/paperless/data
      - /opt/docker/appdata/paperless/media:/usr/src/paperless/media
      - /mnt/scan/Export:/usr/src/paperless/export
      - /mnt/scan/Consume:/usr/src/paperless/consume
    networks:
      - proxy
      - paperless
    depends_on:
      - database
      - redis
      - gotenberg
      - tika

  redis:
    container_name: paperless-redis
    image: redis:8.0.3-alpine
    restart: unless-stopped
    volumes:
      - /opt/docker/appdata/paperless/redis:/data
    networks:
      - paperless

  gotenberg:
    container_name: paperless-gotenberg
    image: gotenberg/gotenberg:8.21.1
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless

  tika:
    container_name: paperless-tika
    image: ghcr.io/paperless-ngx/tika:2.9.1-minimal
    restart: unless-stopped
    networks:
      - paperless

networks:
  proxy:
    external: true
  paperless:
    external: true
