services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy
    restart: unless-stopped
    command: serve
    environment:
      TZ: Europe/Vienna
    volumes:
      - /opt/docker/appdata/ntfy/config:/etc/ntfy
      - /opt/docker/appdata/ntfy/cache:/var/cache/ntfy
      - /opt/docker/appdata/ntfy/database/user.db:/var/lib/ntfy/user.db
    networks:
      - proxy

networks:
  proxy:
    external: true
