services:
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: unless-stopped
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/lidarr/config:/config
      - /mnt/music:/music
      - /mnt/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    external: true
