services:
  code-server:
    container_name: code-server
    image: linuxserver/code-server
    restart: unless-stopped
    ports:
      - 8888:8443
    env_file:
      - .env
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/code-server/config:/config
      - /opt/docker/:/opt/docker/
    networks:
      - proxy

networks:
  proxy:
    external: true
