services:
  code-server:
    container_name: code-server
    image: linuxserver/code-server:4.96.4
    restart: unless-stopped
    ports:
      - 8888:8443
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
      PROXY_DOMAIN: ${PROXY_DOMAIN}
    volumes:
      - /opt/docker/appdata/code-server/config:/config
      - /opt/docker:/opt/docker
    networks:
      - proxy

networks:
  proxy:
    external: true
