services:
  code-server:
    container_name: code-server
    image: linuxserver/code-server:4.100.0
    restart: unless-stopped
    ports:
      - "8888:8443"
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/code-server/config:/config
      - /opt/docker:/opt/docker
    networks:
      - proxy

networks:
  proxy:
    external: true
