services:
  changedetection:
    container_name: changedetection
    image: linuxserver/changedetection.io
    restart: unless-stopped
    volumes:
      - /opt/docker/appdata/changedetection/config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
