services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr
    restart: unless-stopped
    environment:
      TZ: Europe/Vienna
    volumes:
      - /opt/docker/appdata/jellyseerr/config:/app/config
    networks:
      - proxy

networks:
  proxy:
    external: true
