services:
  database:
    container_name: freshrss-database
    image: postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/docker/appdata/freshrss/database:/var/lib/postgresql/data
    networks:
      - freshrss
      
  freshrss:
    container_name: freshrss
    image: linuxserver/freshrss:1.26.1
    restart: unless-stopped
    ports:
      - "8082:80"
    env_file:
      - .env
    volumes:
      - /opt/docker/appdata/freshrss/config:/config
    networks:
      - proxy
      - freshrss
    depends_on:
      - database
      
networks:
  proxy:
    external: true
  freshrss:
    external: true
