api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  spice:
    address: ":3128"
  spice-tls:
    address: ":61005"
  checkmk:
    address: ":8000"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: adrian@zech.co
      storage: acme.json
      dnsChallenge:
        provider: cloudflare

