services:
  database:
    container_name: jellystat-database
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    labels:
      - wud.watch=false
    volumes:
      - /opt/docker/appdata/jellystat/database:/var/lib/postgresql/data
    networks:
      - jellystat

  jellystat:
    container_name: jellystat
    image: cyfershepard/jellystat
    restart: unless-stopped
    ports:
      - 3003:3000
    env_file:
      - .env
    environment:
      TZ: Europe/Vienna
      DB: postgres
      POSTGRES_IP: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /opt/docker/appdata/jellystat/backup-data:/app/backend/backup-data
    networks:
      - proxy
      - jellystat
    depends_on:
      - database

networks:
  proxy:
    external: true
  jellystat:
    external: true