services:
  hoarder:
    container_name: hoarder
    image:  ghcr.io/hoarder-app/hoarder:0.21.0
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      DISABLE_SIGNUPS: true
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      OAUTH_WELLKNOWN_URL: ${OAUTH_WELLKNOWN_URL}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_SCOPE: ${OAUTH_SCOPE}
      OAUTH_PROVIDER_NAME: ${OAUTH_PROVIDER_NAME}
      OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: ${OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - /opt/docker/appdata/hoarder/data:/data
    networks:
      - hoarder
    depends_on:
      - chrome
      - meilisearch

  chrome:
    container_name: hoarder-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder

  meilisearch:
    container_name: hoarder-meilisearch
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: true
    volumes:
      - /opt/docker/appdata/hoarder/meilisearch:/meili_data
    networks:
      - hoarder

networks:
  proxy:
    external: true
  hoarder:
    external: true
