services:
  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.8.2
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitoring

networks:
  monitoring:
    external: true
