services:
  youtube-dl:
    container_name: youtube-dl
    image: linuxserver/code-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROXY_DOMAIN: ${BASE_URL}
    labels:
      traefik.enable: true
      traefik.http.routers.youtube-dl.entrypoints: http
      traefik.http.routers.youtube-dl.rule: Host(`${BASE_URL}`)
      traefik.http.middlewares.youtube-dl-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.youtube-dl.middlewares: youtube-dl-https-redirect
      traefik.http.routers.youtube-dl-secure.entrypoints: https
      traefik.http.routers.youtube-dl-secure.rule: Host(`${BASE_URL}`)
      traefik.http.routers.youtube-dl-secure.tls: true
      traefik.http.routers.youtube-dl-secure.service: youtube-dl
      traefik.http.routers.youtube-dl-secure.middlewares: secured@file
      traefik.http.services.youtube-dl.loadbalancer.server.port: ${PORT}
      traefik.docker.network: proxy
    volumes:
      - /opt/docker/appdata/youtube-dl/ytdl:/ytdl
      - /opt/docker/appdata/youtube-dl/config:/config
      - /mnt/private:/private
    networks:
      - proxy

networks:
  proxy:
    external: true
