services:
  youtube-dl:
    container_name: youtube-dl
    image: linuxserver/code-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/youtube-dl/ytdl:/ytdl
      - /opt/docker/appdata/youtube-dl/config:/config
      - /mnt/private:/private
    networks:
      - proxy

networks:
  proxy:
    external: true
