services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:2.49.1
    restart: unless-stopped
    ports:
      - "8089:80"
    volumes:
      - /opt/docker/appdata/wallos/db:/var/www/html/db
      - /opt/docker/appdata/wallos/logos:/var/www/html/images/uploads/logos
    networks:
      - proxy

networks:
  proxy:
    external: true
