services:
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf
    restart: unless-stopped
    environment:
      TZ: Europe/Vienna
      PGID: 1000
      PUID: 1000
    volumes:
      - /opt/docker/appdata/stirling-pdf/tessdata:/usr/share/tesseract-ocr/4.00/tessdata
      - /opt/docker/appdata/stirling-pdf/configs:/configs
    networks:
      - proxy

networks:
  proxy:
    external: true
