services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:1.6.0
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.bazarr.rule: "Host(`bazarr.zech.co`)"
      traefik.http.routers.bazarr.entrypoints: "websecure"
      traefik.http.routers.bazarr.tls: "true"
      traefik.http.routers.bazarr-api.rule: "Host(`bazarr.zech.co`) && (Path(`/api`) || PathPrefix(`/api/`))"
      traefik.http.routers.bazarr-api.entrypoints: "websecure"
      traefik.http.routers.bazarr-api.tls: "true"
      traefik.http.routers.bazarr-api.priority: "100"
      traefik.http.routers.bazarr-api.middlewares: "security-headers@file,compression@file"
      traefik.http.routers.bazarr-api.service: "bazarr"
      traefik.http.routers.bazarr.middlewares: "authentik@file,security-headers@file,compression@file"
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"
    environment:
      TZ: Europe/Vienna
      PUID: 1000
      PGID: 1000
    volumes:
      - /opt/appdata/bazarr/config:/config
      - /mnt/tv:/tv
      - /mnt/movies:/movies
    networks:
      - proxy

networks:
  proxy:
    external: true
