services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome
    restart: unless-stopped
    ports:
      - 4533:4533
    env_file:
      - .env
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
    volumes:
      - /opt/docker/appdata/navidrome/data:/data
      - /mnt/music:/music
    networks:
      - proxy

networks:
  proxy:
    external: true
