services:
  homepage:
    container_name: homepage
    image: gethomepage/homepage:v0.10.9
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/appdata/homepage/config:/app/config
    networks:
      - proxy

networks:
  proxy:
    external: true
