services:
  homepage:
    container_name: homepage
    image: gethomepage/homepage:v1.4.0
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/appdata/homepage/config:/app/config
    networks:
      - proxy

networks:
  proxy:
    external: true
