services:
  linkstack:
    container_name: linkstack
    image: linkstackorg/linkstack:latest
    restart: unless-stopped
    ports:
      - 4443:443
    environment:
      TZ: Europe/Vienna
    volumes:
      - /opt/docker/appdata/linkstack/htdocs:/htdocs
    networks:
      - proxy

networks:
  proxy:
    external: true
