services:
  socket-proxy:
    container_name: beszel-agent-socket-proxy
    image: tecnativa/docker-socket-proxy:v0.5.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://127.0.0.1:2375/version"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - 127.0.0.1:2375:2375
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy

  beszel-agent:
    container_name: beszel-agent
    image: henrygd/beszel-agent:0.18.8
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      DOCKER_HOST: tcp://127.0.0.1:2375
    volumes:
      - ../docker/appdata/beszel-agent:/var/lib/beszel-agent
    depends_on:
      socket-proxy:
        condition: service_healthy

networks:
  socket-proxy:
    internal: true
