name: Auto Deploy on Push

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Delay the execution by 3 minutes
      run: |
          echo "Waiting for 3 minutes to batch events..."
          sleep 180

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Deploy changed containers
      run: |
        cd "$GITHUB_WORKSPACE"
        git pull origin main

        CHANGED_CONTAINERS=$(git diff --name-only HEAD~1 HEAD | grep "^containers/" | cut -d'/' -f2 | sort -u)

        if [ -z "$CHANGED_CONTAINERS" ]; then
            echo "No relevant changes detected."
            exit 0
        fi

        for container in $CHANGED_CONTAINERS; do
            echo "Updating $container..."
            cd containers/$container
            docker compose pull
            docker compose up -d
            cd ../..
        done
